Style/ModuleFunction:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/ClassAndModuleChildren:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 25

Style/RedundantReturn:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false
